# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccin" do
  desc "An advanced CLI for generating CRUD applications with modular architecture"
  homepage "https://github.com/chrisloarryn/homebrew-ccin"
  version "0.0.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccin"

  on_macos do
    url "https://github.com/chrisloarryn/homebrew-ccin/releases/download/v0.0.12/ccin_Darwin_all.tar.gz"
    sha256 "70273a078402f9da047b4a6f1e75c313020a85443cada87b845e457fe552567c"
  end

  on_linux do
    on_intel do
      url "https://github.com/chrisloarryn/homebrew-ccin/releases/download/v0.0.12/ccin_Linux_x86_64.tar.gz"
      sha256 "d4d88f0c012901a0dd8d31c12fa6ef06a711fc5915634be98d8ec40733e45daf"
    end
    on_arm do
      url "https://github.com/chrisloarryn/homebrew-ccin/releases/download/v0.0.12/ccin_Linux_arm64.tar.gz"
      sha256 "7d0e6273240eab825f6b8320c52874bf78c980bcb40ad95c7bf1c4d38f918ed7"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccin"]
    end
  end

  caveats do
    "After installation, you can use ccin to generate CRUD applications:"
    "  ccin generate nestjs my-api --domain user"
    "  ccin generate go-gin my-gin-api --domain product --grpc"
    "  ccin generate go-fiber my-fiber-api --domain order"
  end

  # No zap stanza required
end
